apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: capstone-cluster
  region: us-west-2

nodeGroups:
  - name: capstone-ng
    instanceType: t3.medium
    desiredCapacity: 2
    volumeSize: 30
    ssh:
      publicKeyName: udacity
