apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-webapp
  template:
    metadata:
      labels:
        app: sample-webapp
    spec:
      containers:
        - name: sample-webapp
          image: 089634162715.dkr.ecr.us-west-2.amazonaws.com/capstone:latest
          imagePullPolicy: "Always"
          ports:
            - name: http
              containerPort: 80
