apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-deploy
spec:
  selector:
    matchLabels:
      app: todo-app
  replicas: 2
  template:
    metadata:
      labels:
        app: todo-app
    spec:
      containers:
        - name: todo-app
          image: 089634162715.dkr.ecr.us-west-2.amazonaws.com/capstone:latest
          imagePullPolicy: "Always"
          ports:
            - name: todo-http
              containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: todo-svc
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  selector:
    app: todo-app
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer

